# Generated by Django 5.2.1 on 2025-05-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='emergency contact'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='enrollment date'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='guardian contact'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='guardian name'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='grade level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.TextField(blank=True, default='', verbose_name='interests'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='school name'),
        ),
    ]
