# Generated by Django 5.2.1 on 2025-05-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='certifications',
            field=models.TextField(blank=True, default='', verbose_name='certifications'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='contact number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='employee ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='hire date'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_level',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='teaching level'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='qualification'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_specialization',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='subject specialization'),
        ),
    ]
