# Generated by Django 6.0 on 2025-12-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0002_teacher_certifications_teacher_contact_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teaching_level',
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_hours',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='contact hours'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='office_location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='office location'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_specialization',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='subject specialization'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='years_of_experience',
            field=models.IntegerField(default=0, verbose_name='years of experience'),
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_students', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Class',
                'verbose_name_plural': 'Teacher Classes',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('active_courses', models.IntegerField(default=0)),
                ('pending_assignments', models.IntegerField(default=0)),
                ('average_class_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Stats',
                'verbose_name_plural': 'Teacher Stats',
            },
        ),
    ]
