# Generated by Django 5.2.1 on 2025-05-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email_secondary',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='secondary email'),
        ),
        migrations.AddField(
            model_name='parent',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='emergency contact name'),
        ),
        migrations.AddField(
            model_name='parent',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='emergency contact phone'),
        ),
        migrations.AddField(
            model_name='parent',
            name='employer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='employer'),
        ),
        migrations.AddField(
            model_name='parent',
            name='preferred_contact_method',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='preferred contact method'),
        ),
        migrations.AddField(
            model_name='parent',
            name='relationship_to_student',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='relationship to student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='secondary_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='secondary phone'),
        ),
        migrations.AddField(
            model_name='parent',
            name='work_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='work phone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='occupation'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='phone number'),
        ),
    ]
