# Generated by Django 6.0 on 2025-12-19 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('grade', models.CharField(choices=[('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jss_1', 'JSS 1'), ('jss_2', 'JSS 2'), ('jss_3', 'JSS 3'), ('sss_1', 'SSS 1'), ('sss_2', 'SSS 2'), ('sss_3', 'SSS 3')], max_length=50, verbose_name='grade')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50, verbose_name='level')),
                ('language', models.CharField(default='English', max_length=50, verbose_name='language')),
                ('duration', models.CharField(help_text='e.g., 4 weeks', max_length=50, verbose_name='duration')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('thumbnail', models.URLField(blank=True, default='/placeholder.svg', verbose_name='thumbnail')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='total lessons')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('achievement_type', models.CharField(choices=[('course_completion', 'Course Completion'), ('streak', 'Learning Streak'), ('score', 'High Score'), ('milestone', 'Milestone')], max_length=50, verbose_name='type')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='icon')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='pending', max_length=20, verbose_name='status')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses', models.IntegerField(default=0, verbose_name='total courses')),
                ('completed_courses', models.IntegerField(default=0, verbose_name='completed courses')),
                ('current_streak', models.IntegerField(default=0, verbose_name='current streak (days)')),
                ('total_hours', models.IntegerField(default=0, verbose_name='total hours')),
                ('average_score', models.FloatField(default=0.0, verbose_name='average score')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='last activity')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student stats',
                'verbose_name_plural': 'student stats',
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='progress percentage')),
                ('completed_lessons', models.IntegerField(default=0, verbose_name='completed lessons')),
                ('time_spent_minutes', models.IntegerField(default=0, verbose_name='time spent (minutes)')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='last accessed')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('average_score', models.FloatField(default=0.0, verbose_name='average score')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student progress',
                'verbose_name_plural': 'student progress',
                'ordering': ['-last_accessed'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
