# Generated by Django 6.0 on 2025-12-19 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['student', 'status'], name='courses_ass_student_49b205_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course'], name='courses_ass_course__33d84f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='courses_ass_due_dat_e405cf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='courses_ass_status_1c47cf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject'], name='courses_cou_subject_f5fc79_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['grade'], name='courses_cou_grade_fc83d8_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='courses_cou_level_bf0a39_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published'], name='courses_cou_is_publ_4b99b9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', 'grade'], name='courses_cou_subject_376bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'course'], name='courses_stu_student_c8e07c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['is_completed'], name='courses_stu_is_comp_f15354_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['last_accessed'], name='courses_stu_last_ac_0bb1a4_idx'),
        ),
    ]
